title: "Communication Complexity for multi party graph problems"
description: "A set of proof for lower bounds on graph problems, specifically
focusing on problems of identifying graph proporties when each parties input is
some portion of the graph."
theme: jekyll-theme-tactile
markdown: kramdown
kramdown:
  math_engine: mathjax
