title: Communication Complexity for multi party graph problems
description: "A set of proof for lower bounds on graph problems, specifically
focusing on problems of identifying graph proporties when each parties input is
some portion of the graph."
remote-theme: pages-themes/@tactile@v0.2.0
plugins:
- jekyll-remote-theme
